<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" type="text/css" href="styles.css">
    <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">
    <link href="https://vjs.zencdn.net/7.15.4/video-js.css" rel="stylesheet">

    <link rel="shortcut icon" href="../img/favicon.ico" type="image/x-icon">
    <link rel="icon" sizes="192x192" href="../img/favicon.ico">

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/aws-sdk/2.1106.0/aws-sdk.min.js"></script>
    <script src="https://vjs.zencdn.net/7.15.4/video.js"></script>

    <title>The Tony Chase Archive</title>
</head>
<body>
    <div class="update-banner" id="updateBanner">
        <p id="updateP"><strong>Important Update: </strong><a href="http://wiki.tonychasearchive.com/index.php/Main_Page">Tony Chase Wiki has been started!</a> The <a href="https://www.youtube.com/channel/UC4sfPcxykL4NLc72WnchiyA">channel (click me)</a> is slowly uploading the 2022 videos.</p>
        <button id="closeUpdateButton">Close</button>
    </div>
    <header>
        <a id="titleLink" href="http://tonychasearchive.com"><h1>Tony Chase Video Archive</h1></a>
        <h2 id="customHeader2"></h2>
        <div id="quoteOfTheDay">
            <h2>Quote of the Day</h2>
            <p id="quoteText"></p>
            <p id="quoteAuthorDisplay"></p>
        </div>  
    </header>
    <main>
        <p></p>
        <div id="quoteInputContainer" class="quote-container">
        <h2>Add Your Quote <span class="closexd">x</span></h2>
            <form id="quoteInputForm" action="/quote_scripts/process_quote.php" method="post">
                <label for="quoteContent">Quote Content:</label>
                <textarea id="quoteContent" name="quoteContent" rows="4" cols="50" required></textarea>
                <br>
                <label for="quoteAuthorInput" class="quote-author">Quote Author:</label>
                <input type="text" id="quoteAuthorInput" name="quoteAuthor" required>
                <br>
                <button type="submit">Submit Quote</button>
            </form>
        </div>

        <p>Total Videos: <span id="totalVideoCount">0</span></p>
        <button id="toggleVideoListButton">Toggle Video List</button>
        <p></p>
        <input type="text" id="searchInput" placeholder="Search videos">

        <div id="searchResults">
            <!-- Search results will be displayed here -->
        </div>
        <div id="infoContainer">
            <div id="discordAndAbout">
                <a id="discordLink" href="https://discord.gg/beW5rY5Qrj">> Join our Discord Server</a>
                <br>
                <a id="aboutLink" href="../about/">> About Tony Chase</a>
                <br>
                <a id="newsLink" href="../news/">> News about Tony and the Archive</a>
                <br>
                <a id="noteLink" href="http://wiki.tonychasearchive.com/index.php/Main_Page">> Tony Chase Wiki</a>
                <br>
                <a id="cashLink" href="https://cash.app/$tonychasearchive">> Donate to the Archive</a>
                <br>
                <a id="settingsLink" href="#">> Settings</a>
            </div>
        </div>

        <div id="settingsPanel" class="settings-panel">
            <label for="darkModeToggle">Dark Mode</label>
            <input type="checkbox" id="darkModeToggle">
            <br>
            <input type="checkbox" id="watchHistoryToggle" checked>
            <label for="watchHistoryToggle">Keep Watch History</label>
        </div>

    <ul id="videoList">
        <!-- Video list will be generated by list.js -->
    </ul>
    </main>
    <section id="videoOfTheDaySection">
    <h2>Video of the Day</h2>
    <div id="currentVideo">Current Video: No video playing</div>
    <p></p>
    <button id="randomVideoButton">Random Video (In new window)</button>
    <button id="newVideo">New Video (In tab)</button>
    <button id="crazyButton">Play a lot of videos (Loud warning)</button>
    <p></p>
    <div id="randomVideoContainer">
        <!-- The random videos will be displayed here -->
            <div id="video-container"></div>
    </div>
    <section id="watchHistorySection">
        <h2>Watch History</h2>
        <ul id="watchHistoryList"></ul>
    </section>
    </section>
    <script src="js/list.js"></script>
    <script src="/quote_scripts/quote.js"></script>
    <script src="js/search.js"></script>
    <script src="js/banner.js"></script>
    <script src="js/settings.js"></script>
    <!-- <script src="js/tonyplayer.js"></script> -->
    <hr>
    <footer>
        This website has been crafted with ❤️ by satellite controllers stationed in satellite control rooms.
    </footer>
</body>
</html>
